# Generated by Django 6.0.4 on 2026-04-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='dateEnded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='grade',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AddField(
            model_name='series',
            name='status',
            field=models.CharField(default='ongoing', max_length=20),
        ),
    ]
