# Generated by Django 6.0.4 on 2026-04-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_series_dateended_series_grade_series_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='grade',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
