# Generated by Django 6.0.4 on 2026-04-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_series_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
