# Generated by Django 6.0.4 on 2026-04-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_series_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
