# Generated by Django 6.0.4 on 2026-05-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_series_poster_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='collection_type',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('watchLater', 'Watch Later')], default='backlog', max_length=20),
        ),
    ]
